javascript const loginBtn = document.getElementById('loginBtn'); const signupBtn = document.getElementById('signupBtn'); const loginModal = document.getElementById('loginModal'); const signupModal = document.getElementById('signupModal'); const closeLogin = document.querySelector('.modal .close'); const closeSignup = document.querySelector('.modal .close'); const loginForm = document.getElementById('loginForm'); const signupForm = document.getElementById('signupForm'); const cartLink = document.getElementById('cartLink'); const cartCount = document.getElementById('cartCount'); const cartItems = document.getElementById('cartItems'); const checkoutBtn = document.getElementById('checkoutBtn');
let cart = []; let currentUser = null;
// Open login modal loginBtn.addEventListener('click', () => { loginModal.style.display = 'block'; });
// Open signup modal signupBtn.addEventListener('click', () => { signupModal.style.display = 'block'; });
// Close modals closeLogin.addEventListener('click', () => { loginModal.style.display = 'none'; });
closeSignup.addEventListener('click', () => { signupModal.style.display = 'none'; });
window.addEventListener('click', (event) => { if (event.target === loginModal || event.target === signupModal) { loginModal.style.display = 'none'; signupModal.style.display = 'none'; } });
// Login form submission loginForm.addEventListener('submit', (event) => { event.preventDefault(); const email = loginForm.email.value; const password = loginForm.password.value; // Perform login logic here (e.g., check with a server or database) // For simplicity, we'll assume the user exists and log them in currentUser = { email: email, password: password }; loginModal.style.display = 'none'; updateUI(); });
// Signup form submission signupForm.addEventListener('submit', (event) => { event.preventDefault(); const email = signupForm.email.value; const password = signupForm.password.value; const confirmPassword = signupForm.confirmPassword.value; // Perform signup logic here (e.g., create a new user on the server) // For simplicity, we'll assume the user is created successfully if (password === confirmPassword) { currentUser = { email: email, password: password }; signupModal.style.display = 'none'; updateUI(); } else { alert('Passwords do not match.'); } });
// Add product to cart document.addEventListener('click', (event) => { if (event.target.tagName === 'BUTTON' && event.target.dataset.product) { const product = event.target.dataset.product; addItemToCart(product); updateUI(); } });
// Update UI based on user state and cart contents function updateUI() { if (currentUser) { cartLink.textContent = Cart (${cart.length